-- ============================================================
-- Denial Navigator - CARC Code Seed Data
-- Claim Adjustment Reason Codes (ANSI X12 835, CAS02)
--
-- Source:  https://x12.org/codes/claim-adjustment-reason-codes
-- Fetched: 2026-09-05   (source page last updated 2025-11-01)
-- Codes:   405 (10 deactivated, marked is_active = false)
--
-- IMPORTANT, read before relying on this in production:
--   * Descriptions were extracted from the published X12 page and SOME ARE
--     ABBREVIATED relative to the official wording. They are accurate in
--     meaning but are not a verbatim reproduction of the standard. Validate
--     against the official X12 publication before billing decisions rest on
--     the exact text.
--   * X12 revises this list roughly three times a year. Re-run this import
--     after each revision; it is idempotent.
--   * The `category` column is a LOCAL grouping for the UI. X12 does not
--     categorise CARCs - these buckets are keyword-derived, not authoritative.
--
-- Idempotent: safe to re-run against an existing database.
-- ============================================================

INSERT INTO carc_codes (code, description, category, is_active) VALUES
  ('1', 'Deductible Amount', 'patient_responsibility', true),
  ('2', 'Coinsurance Amount', 'patient_responsibility', true),
  ('3', 'Co-payment Amount', 'patient_responsibility', true),
  ('4', 'The procedure code is inconsistent with the modifier used', 'coding_error', true),
  ('5', 'The procedure code/type of bill is inconsistent with the place of service', 'coding_error', true),
  ('6', 'The procedure/revenue code is inconsistent with the patient''s age', 'coding_error', true),
  ('7', 'The procedure/revenue code is inconsistent with the patient''s gender', 'coding_error', true),
  ('8', 'The procedure code is inconsistent with the provider type/specialty', 'coding_error', true),
  ('9', 'The diagnosis is inconsistent with the patient''s age', 'coding_error', true),
  ('10', 'The diagnosis is inconsistent with the patient''s gender', 'coding_error', true),
  ('11', 'The diagnosis is inconsistent with the procedure', 'coding_error', true),
  ('12', 'The diagnosis is inconsistent with the provider type', 'coding_error', true),
  ('13', 'The date of death precedes the date of service', 'other', true),
  ('14', 'The date of birth follows the date of service', 'other', true),
  ('15', 'The authorization number is missing, invalid, or does not apply', 'lack_of_preauth', true),
  ('16', 'Claim/service lacks information or has submission/billing error(s)', 'missing_info', true),
  ('17', 'Requested information was not provided or was insufficient/incomplete', 'missing_info', true),
  ('18', 'Exact duplicate claim/service', 'duplicate_claim', true),
  ('19', 'This is a work-related injury/illness and thus the liability of the Worker''s Compensation Carrier', 'other', true),
  ('20', 'This injury/illness is covered by the liability carrier', 'other_liability', true),
  ('21', 'This injury/illness is the liability of the no-fault carrier', 'other_liability', true),
  ('22', 'This care may be covered by another payer per coordination of benefits', 'other', true),
  ('23', 'The impact of prior payer(s) adjudication including payments and/or adjustments', 'other', true),
  ('24', 'Charges are covered under a capitation agreement/managed care plan', 'other', true),
  ('25', 'Payment denied. Your Stop loss deductible has not been met', 'other', true),
  ('26', 'Expenses incurred prior to coverage', 'non_covered_service', true),
  ('27', 'Expenses incurred after coverage terminated', 'non_covered_service', true),
  ('28', 'Coverage not in effect at the time the service was provided', 'non_covered_service', true),
  ('29', 'The time limit for filing has expired', 'timely_filing', true),
  ('30', 'Payment adjusted because the patient has not met required eligibility, spend down, waiting, or residency requirements', 'other', true),
  ('31', 'Patient cannot be identified as our insured', 'other', true),
  ('32', 'Our records indicate the patient is not an eligible dependent', 'other', true),
  ('33', 'Insured has no dependent coverage', 'non_covered_service', true),
  ('34', 'Insured has no coverage for newborns', 'non_covered_service', true),
  ('35', 'Lifetime benefit maximum has been reached', 'non_covered_service', true),
  ('36', 'Balance does not exceed co-payment amount', 'other', true),
  ('37', 'Balance does not exceed deductible', 'other', true),
  ('38', 'Services not provided or authorized by designated (network/primary care) providers', 'lack_of_preauth', true),
  ('39', 'Services denied at the time authorization/pre-certification was requested', 'lack_of_preauth', true),
  ('40', 'Charges do not meet qualifications for emergent/urgent care', 'other', true),
  ('41', 'Discount agreed to in Preferred Provider contract', 'contractual', true),
  ('42', 'Charges exceed our fee schedule or maximum allowable amount', 'contractual', true),
  ('43', 'Gramm-Rudman reduction', 'other', true),
  ('44', 'Prompt-pay discount', 'contractual', true),
  ('45', 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement', 'contractual', true),
  ('46', 'This (these) service(s) is (are) not covered', 'non_covered_service', true),
  ('47', 'This (these) diagnosis(es) is (are) not covered, missing, or are invalid', 'missing_info', true),
  ('48', 'This (these) procedure(s) is (are) not covered', 'non_covered_service', true),
  ('49', 'This is a non-covered service because it is a routine/preventive exam', 'non_covered_service', true),
  ('50', 'These are non-covered services because this is not deemed a ''medical necessity''', 'medical_necessity', true),
  ('51', 'These are non-covered services because this is a pre-existing condition', 'non_covered_service', true),
  ('52', 'The referring/prescribing/rendering provider is not eligible', 'other', true),
  ('53', 'Services by an immediate relative or member of same household not covered', 'non_covered_service', true),
  ('54', 'Multiple physicians/assistants are not covered in this case', 'non_covered_service', true),
  ('55', 'Procedure/treatment/drug is deemed experimental/investigational by the payer', 'medical_necessity', true),
  ('56', 'Procedure/treatment has not been deemed ''proven to be effective''', 'other', true),
  ('57', 'Payment denied/reduced because payer deems information submitted insufficient', 'missing_info', true),
  ('58', 'Treatment deemed to have been rendered in inappropriate or invalid place of service', 'other', true),
  ('59', 'Processed based on multiple or concurrent procedure rules', 'other', true),
  ('60', 'Charges for outpatient services not covered when performed within period prior/after inpatient', 'non_covered_service', true),
  ('61', 'Adjusted for failure to obtain second surgical opinion', 'other', true),
  ('62', 'Payment denied/reduced for absence of, or exceeded, pre-certification/authorization', 'lack_of_preauth', true),
  ('63', 'Correction to a prior claim', 'other', true),
  ('64', 'Denial reversed per Medical Review', 'other', true),
  ('65', 'Procedure code was incorrect. This payment reflects correct code', 'coding_error', true),
  ('66', 'Blood Deductible', 'patient_responsibility', true),
  ('67', 'Lifetime reserve days', 'other', true),
  ('68', 'DRG weight', 'other', true),
  ('69', 'Day outlier amount', 'other', true),
  ('70', 'Cost outlier - Adjustment to compensate for additional costs', 'other', true),
  ('71', 'Primary Payer amount', 'other', true),
  ('72', 'Coinsurance day', 'other', true),
  ('73', 'Administrative days', 'other', true),
  ('74', 'Indirect Medical Education Adjustment', 'other', true),
  ('75', 'Direct Medical Education Adjustment', 'other', true),
  ('76', 'Disproportionate Share Adjustment', 'other', true),
  ('77', 'Covered days', 'other', true),
  ('78', 'Non-Covered days/Room charge adjustment', 'non_covered_service', true),
  ('79', 'Cost Report days', 'other', true),
  ('80', 'Outlier days', 'other', true),
  ('81', 'Discharges', 'other', true),
  ('82', 'PIP days', 'other', true),
  ('83', 'Total visits', 'other', true),
  ('84', 'Capital Adjustment', 'other', true),
  ('85', 'Patient Interest Adjustment', 'other', true),
  ('86', 'Statutory Adjustment', 'other', true),
  ('87', 'Transfer amount', 'other', true),
  ('88', 'Adjustment amount represents collection against receivable from prior overpayment', 'other', true),
  ('89', 'Professional fees removed from charges', 'other', true),
  ('90', 'Ingredient cost adjustment', 'other', true),
  ('91', 'Dispensing fee adjustment', 'other', true),
  ('92', 'Claim Paid in full', 'other', true),
  ('93', 'No Claim level Adjustments', 'other', true),
  ('94', 'Processed in Excess of charges', 'other', true),
  ('95', 'Plan procedures not followed', 'other', true),
  ('96', 'Non-covered charge(s)', 'non_covered_service', true),
  ('97', 'The benefit for this service is included in the payment/allowance for another service', 'bundled_service', true),
  ('98', 'The hospital must file the Medicare claim for this inpatient non-physician service', 'other', true),
  ('99', 'Medicare Secondary Payer Adjustment Amount', 'other', true),
  ('100', 'Payment made to patient/insured/responsible party', 'other', true),
  ('101', 'Predetermination: anticipated payment upon completion of services', 'other', true),
  ('102', 'Major Medical Adjustment', 'other', true),
  ('103', 'Provider promotional discount', 'contractual', true),
  ('104', 'Managed care withholding', 'other', true),
  ('105', 'Tax withholding', 'other', true),
  ('106', 'Patient payment option/election not in effect', 'other', true),
  ('107', 'The related or qualifying claim/service was not identified on this claim', 'other', true),
  ('108', 'Rent/purchase guidelines were not met', 'other', true),
  ('109', 'Claim/service not covered by this payer/contractor', 'non_covered_service', true),
  ('110', 'Billing date predates service date', 'other', true),
  ('111', 'Not covered unless the provider accepts assignment', 'non_covered_service', true),
  ('112', 'Service not furnished directly to the patient and/or not documented', 'other', true),
  ('113', 'Payment denied because service/procedure was provided outside United States or as result of war', 'other', true),
  ('114', 'Procedure/product not approved by the Food and Drug Administration', 'other', true),
  ('115', 'Procedure postponed, canceled, or delayed', 'other', true),
  ('116', 'The advance indemnification notice signed by patient did not comply with requirements', 'other', true),
  ('117', 'Transportation is only covered to closest facility that can provide necessary care', 'other', true),
  ('118', 'ESRD network support adjustment', 'other', true),
  ('119', 'Benefit maximum for this time period or occurrence has been reached', 'non_covered_service', true),
  ('120', 'Patient is covered by a managed care plan', 'other', true),
  ('121', 'Indemnification adjustment - compensation for outstanding member responsibility', 'other', true),
  ('122', 'Psychiatric reduction', 'other', true),
  ('123', 'Payer refund due to overpayment', 'other', true),
  ('124', 'Payer refund amount - not our patient', 'other', true),
  ('125', 'Submission/billing error(s)', 'other', true),
  ('126', 'Deductible -- Major Medical', 'patient_responsibility', true),
  ('127', 'Coinsurance -- Major Medical', 'patient_responsibility', true),
  ('128', 'Newborn''s services are covered in the mother''s Allowance', 'other', true),
  ('129', 'Prior processing information appears incorrect', 'other', true),
  ('130', 'Claim submission fee', 'other', true),
  ('131', 'Claim specific negotiated discount', 'contractual', true),
  ('132', 'Prearranged demonstration project adjustment', 'other', true),
  ('133', 'The disposition of this service line is pending further review', 'other', true),
  ('134', 'Technical fees removed from charges', 'other', true),
  ('135', 'Interim bills cannot be processed', 'other', true),
  ('136', 'Failure to follow prior payer''s coverage rules', 'non_covered_service', true),
  ('137', 'Regulatory Surcharges, Assessments, Allowances or Health Related Taxes', 'other', true),
  ('138', 'Appeal procedures not followed or time limits not met', 'appeal_process', true),
  ('139', 'Contracted funding agreement - Subscriber employed by the provider of services', 'other', true),
  ('140', 'Patient/Insured health identification number and name do not match', 'other', true),
  ('141', 'Claim spans eligible and ineligible periods of coverage', 'non_covered_service', true),
  ('142', 'Monthly Medicaid patient liability amount', 'other', true),
  ('143', 'Portion of payment deferred', 'other', true),
  ('144', 'Incentive adjustment', 'other', true),
  ('145', 'Premium payment withholding', 'other', true),
  ('146', 'Diagnosis was invalid for the date(s) of service reported', 'other', true),
  ('147', 'Provider contracted/negotiated rate expired or not on file', 'contractual', true),
  ('148', 'Information from another provider was not provided or insufficient/incomplete', 'missing_info', true),
  ('149', 'Lifetime benefit maximum has been reached for this service/benefit category', 'non_covered_service', true),
  ('150', 'Payer deems information submitted does not support this level of service', 'other', true),
  ('151', 'Payment adjusted because payer deems information does not support frequency of services', 'other', true),
  ('152', 'Payer deems information submitted does not support this length of service', 'other', true),
  ('153', 'Payer deems information submitted does not support this dosage', 'other', true),
  ('154', 'Payer deems information submitted does not support this day''s supply', 'other', true),
  ('155', 'Patient refused the service/procedure', 'other', true),
  ('156', 'Flexible spending account payments', 'other', true),
  ('157', 'Service/procedure was provided as a result of an act of war', 'other', true),
  ('158', 'Service/procedure was provided outside of the United States', 'other', true),
  ('159', 'Service/procedure was provided as a result of terrorism', 'other', true),
  ('160', 'Injury/illness was result of an activity that is a benefit exclusion', 'other', true),
  ('161', 'Provider performance bonus', 'other', true),
  ('162', 'State-mandated Requirement for Property and Casualty', 'other_liability', true),
  ('163', 'Attachment/other documentation referenced on claim was not received', 'missing_info', true),
  ('164', 'Attachment/other documentation referenced on claim not received timely', 'timely_filing', true),
  ('165', 'Referral absent or exceeded', 'other', true),
  ('166', 'These services were submitted after payer''s responsibility for processing ended', 'other', true),
  ('167', 'This (these) diagnosis(es) is (are) not covered', 'non_covered_service', true),
  ('168', 'Service(s) considered under patient''s medical plan. Benefits not available under dental plan', 'other', true),
  ('169', 'Alternate benefit has been provided', 'other', true),
  ('170', 'Payment is denied when performed/billed by this type of provider', 'other', true),
  ('171', 'Payment denied when performed/billed by provider type in facility type', 'other', true),
  ('172', 'Payment adjusted when performed/billed by provider of this specialty', 'other', true),
  ('173', 'Service/equipment was not prescribed by a physician', 'other', true),
  ('174', 'Service was not prescribed prior to delivery', 'other', true),
  ('175', 'Prescription is incomplete', 'missing_info', true),
  ('176', 'Prescription is not current', 'other', true),
  ('177', 'Patient has not met required eligibility requirements', 'other', true),
  ('178', 'Patient has not met required spend down requirements', 'other', true),
  ('179', 'Patient has not met required waiting requirements', 'other', true),
  ('180', 'Patient has not met required residency requirements', 'other', true),
  ('181', 'Procedure code was invalid on the date of service', 'coding_error', true),
  ('182', 'Procedure modifier was invalid on the date of service', 'coding_error', true),
  ('183', 'The referring provider is not eligible to refer the service billed', 'other', true),
  ('184', 'The prescribing/ordering provider not eligible to prescribe/order service', 'other', true),
  ('185', 'The rendering provider is not eligible to perform the service billed', 'other', true),
  ('186', 'Level of care change adjustment', 'other', true),
  ('187', 'Consumer Spending Account payments', 'other', true),
  ('188', 'This product/procedure only covered when used per FDA recommendations', 'other', true),
  ('189', '''Not otherwise classified'' procedure code billed when specific code exists', 'other', true),
  ('190', 'Payment included in allowance for Skilled Nursing Facility qualified stay', 'other', true),
  ('191', 'Not a work related injury/illness and thus not liability of workers'' compensation carrier', 'other_liability', true),
  ('192', 'Non standard adjustment code from paper remittance', 'other', true),
  ('193', 'Original payment decision is being maintained', 'other', true),
  ('194', 'Anesthesia performed by the operating physician, assistant surgeon or attending physician', 'other', true),
  ('195', 'Refund issued to an erroneous priority payer for this claim/service', 'other', true),
  ('196', 'Claim/service denied based on prior payer''s coverage determination', 'non_covered_service', true),
  ('197', 'Precertification/authorization/notification/pre-treatment absent', 'lack_of_preauth', true),
  ('198', 'Precertification/notification/authorization/pre-treatment exceeded', 'lack_of_preauth', true),
  ('199', 'Revenue code and Procedure code do not match', 'other', true),
  ('200', 'Expenses incurred during lapse in coverage', 'non_covered_service', true),
  ('201', 'Patient responsible for amount of claim through ''set aside arrangement''', 'other', true),
  ('202', 'Non-covered personal comfort or convenience services', 'non_covered_service', true),
  ('203', 'Discontinued or reduced service', 'other', true),
  ('204', 'This service/equipment/drug is not covered under patient''s current benefit plan', 'non_covered_service', true),
  ('205', 'Pharmacy discount card processing fee', 'contractual', true),
  ('206', 'National Provider Identifier - missing', 'missing_info', true),
  ('207', 'National Provider identifier - Invalid format', 'other', true),
  ('208', 'National Provider Identifier - Not matched', 'other', true),
  ('209', 'Provider cannot collect amount from patient per regulatory/agreement', 'other', true),
  ('210', 'Payment adjusted because pre-certification/authorization not timely received', 'timely_filing', true),
  ('211', 'National Drug Codes (NDC) not eligible for rebate, are not covered', 'non_covered_service', true),
  ('212', 'Administrative surcharges are not covered', 'non_covered_service', true),
  ('213', 'Non-compliance with physician self referral prohibition legislation or payer policy', 'other', true),
  ('214', 'Workers'' Compensation claim adjudicated as non-compensable', 'other_liability', true),
  ('215', 'Based on subrogation of a third party settlement', 'other_liability', true),
  ('216', 'Based on the findings of a review organization or payer''s findings', 'other', true),
  ('217', 'Based on payer reasonable and customary fees', 'other', true),
  ('218', 'Based on entitlement to benefits', 'other', true),
  ('219', 'Based on extent of injury', 'other', true),
  ('220', 'The applicable fee schedule/fee database does not contain the billed code', 'contractual', true),
  ('221', 'Claim is under investigation', 'other', true),
  ('222', 'Exceeds the contracted maximum number of hours/days/units by this provider', 'other', true),
  ('223', 'Adjustment code for mandated federal, state or local law/regulation', 'other', true),
  ('224', 'Patient identification compromised by identity theft', 'other', true),
  ('225', 'Penalty or Interest Payment by Payer', 'other', true),
  ('226', 'Information requested from Billing/Rendering Provider not provided timely/sufficiently', 'timely_filing', true),
  ('227', 'Information from patient/insured/responsible party not provided/insufficient/incomplete', 'missing_info', true),
  ('228', 'Denied for failure to supply requested information to previous payer', 'other', true),
  ('229', 'Partial charge amount not considered by Medicare', 'other', true),
  ('230', 'No available or correlating CPT/HCPCS code to describe this service', 'other', true),
  ('231', 'Mutually exclusive procedures cannot be done in same day/setting', 'bundled_service', true),
  ('232', 'Institutional Transfer Amount', 'other', true),
  ('233', 'Services/charges related to hospital-acquired condition or preventable medical error', 'other', true),
  ('234', 'This procedure is not paid separately', 'bundled_service', true),
  ('235', 'Sales Tax', 'other', true),
  ('236', 'Procedure/modifier combination not compatible with another per NCCI', 'bundled_service', true),
  ('237', 'Legislated/Regulatory Penalty', 'other', true),
  ('238', 'Claim spans eligible/ineligible periods; this is reduction for ineligible period', 'other', true),
  ('239', 'Claim spans eligible and ineligible periods. Rebill separate claims', 'other', true),
  ('240', 'The diagnosis is inconsistent with the patient''s birth weight', 'coding_error', true),
  ('241', 'Low Income Subsidy (LIS) Co-payment Amount', 'patient_responsibility', true),
  ('242', 'Services not provided by network/primary care providers', 'missing_info', true),
  ('243', 'Services not authorized by network/primary care providers', 'lack_of_preauth', true),
  ('244', 'Payment reduced to zero due to litigation', 'other', true),
  ('245', 'Provider performance program withhold', 'other', true),
  ('246', 'This non-payable code is for required reporting only', 'other', true),
  ('247', 'Deductible for Professional service in Institutional setting on Institutional claim', 'patient_responsibility', true),
  ('248', 'Coinsurance for Professional service in Institutional setting on Institutional claim', 'patient_responsibility', true),
  ('249', 'This claim has been identified as a readmission', 'other', true),
  ('250', 'Attachment received was incorrect; expected attachment still missing', 'missing_info', true),
  ('251', 'Attachment received was incomplete/deficient; information still needed', 'missing_info', true),
  ('252', 'An attachment/other documentation is required to adjudicate this claim/service', 'missing_info', true),
  ('253', 'Sequestration - reduction in federal payment', 'other', true),
  ('254', 'Claim received by dental plan; benefits not available. Submit to patient''s medical plan', 'other', true),
  ('255', 'The disposition of related Property & Casualty claim is pending due to litigation', 'other', true),
  ('256', 'Service not payable per managed care contract', 'other', true),
  ('257', 'Disposition undetermined during premium payment grace period', 'other', true),
  ('258', 'Claim/service not covered when patient is in custody/incarcerated', 'non_covered_service', true),
  ('259', 'Additional payment for Dental/Vision service utilization', 'other', true),
  ('260', 'Processed under Medicaid ACA Enhanced Fee Schedule', 'contractual', true),
  ('261', 'The procedure or service is inconsistent with the patient''s history', 'coding_error', true),
  ('262', 'Adjustment for delivery cost', 'other', true),
  ('263', 'Adjustment for shipping cost', 'other', true),
  ('264', 'Adjustment for postage cost', 'other', true),
  ('265', 'Adjustment for administrative cost', 'other', true),
  ('266', 'Adjustment for compound preparation cost', 'other', true),
  ('267', 'Claim/service spans multiple months', 'other', true),
  ('268', 'The Claim spans two calendar years', 'other', true),
  ('269', 'Anesthesia not covered for this service/procedure', 'non_covered_service', true),
  ('270', 'Claim received by medical plan; benefits not available. Submit to patient''s dental plan', 'other', true),
  ('271', 'Prior contractual reductions related to current periodic payment', 'contractual', true),
  ('272', 'Coverage/program guidelines were not met', 'non_covered_service', true),
  ('273', 'Coverage/program guidelines were exceeded', 'non_covered_service', true),
  ('274', 'Fee/Service not payable per patient Care Coordination arrangement', 'other', true),
  ('275', 'Prior payer''s patient responsibility not covered', 'non_covered_service', true),
  ('276', 'Services denied by prior payer(s) not covered by this payer', 'non_covered_service', true),
  ('277', 'Disposition undetermined during premium payment grace period (SHOP Exchange)', 'other', true),
  ('278', 'Performance program proficiency requirements not met', 'other', true),
  ('279', 'Services not provided by Preferred network providers', 'missing_info', true),
  ('280', 'Claim received by medical plan; benefits not available. Submit to patient''s Pharmacy plan', 'other', true),
  ('281', 'Deductible waived per contractual agreement', 'contractual', true),
  ('282', 'The procedure/revenue code is inconsistent with the type of bill', 'coding_error', true),
  ('283', 'Attending provider is not eligible to provide direction of care', 'other', true),
  ('284', 'Precertification/authorization/notification/pre-treatment number valid but doesn''t apply', 'lack_of_preauth', true),
  ('285', 'Appeal procedures not followed', 'appeal_process', true),
  ('286', 'Appeal time limits not met', 'appeal_process', true),
  ('287', 'Referral exceeded', 'other', true),
  ('288', 'Referral absent', 'other', true),
  ('289', 'Services considered under dental and medical plans; benefits not available', 'other', true),
  ('290', 'Dental plan claim forwarded to patient''s medical plan', 'other', true),
  ('291', 'Medical plan claim forwarded to patient''s dental plan', 'other', true),
  ('292', 'Medical plan claim forwarded to patient''s pharmacy plan', 'other', true),
  ('293', 'Payment made to employer', 'other', true),
  ('294', 'Payment made to attorney', 'other', true),
  ('295', 'Pharmacy Direct/Indirect Remuneration (DIR)', 'other', true),
  ('296', 'Precertification/authorization/notification/pre-treatment number valid but doesn''t apply to provider', 'lack_of_preauth', true),
  ('297', 'Claim received by medical plan; benefits not available. Submit to patient''s vision plan', 'other', true),
  ('298', 'Medical plan claim forwarded to patient''s vision plan', 'other', true),
  ('299', 'The billing provider is not eligible to receive payment for the service billed', 'other', true),
  ('300', 'Medical Plan claim forwarded to patient''s Behavioral Health Plan', 'other', true),
  ('301', 'Claim received by medical plan; benefits not available. Submit to Behavioral Health Plan', 'other', true),
  ('302', 'Precertification/notification/authorization/pre-treatment time limit expired', 'lack_of_preauth', true),
  ('303', 'Prior payer''s patient responsibility not covered for Qualified Medicare/Medicaid Beneficiaries', 'non_covered_service', true),
  ('304', 'Claim received by medical plan; benefits not available. Submit to patient''s hearing plan', 'other', true),
  ('305', 'Medical plan claim forwarded to patient''s hearing plan', 'other', true),
  ('306', 'Type of bill is inconsistent with the patient status', 'coding_error', true),
  ('307', 'Medicare Maximum Fair Price Standard Default Refund Amount Adjustment', 'other', true),
  ('308', 'Payment adjusted due to contracted funding agreement', 'other', true),
  ('A0', 'Patient refund amount', 'other', true),
  ('A1', 'Claim/Service denied', 'other', true),
  ('A2', 'Contractual adjustment', 'contractual', true),
  ('A3', 'Medicare Secondary Payer liability met', 'other', true),
  ('A4', 'Medicare Claim PPS Capital Day Outlier Amount', 'other', true),
  ('A5', 'Medicare Claim PPS Capital Cost Outlier Amount', 'other', true),
  ('A6', 'Prior hospitalization or 30 day transfer requirement not met', 'other', true),
  ('A7', 'Presumptive Payment Adjustment', 'other', true),
  ('A8', 'Ungroupable DRG', 'other', true),
  ('B1', 'Non-covered visits', 'non_covered_service', true),
  ('B2', 'Covered visits', 'other', true),
  ('B3', 'Covered charges', 'other', true),
  ('B4', 'Late filing penalty', 'timely_filing', true),
  ('B5', 'Coverage/program guidelines were not met or were exceeded', 'non_covered_service', true),
  ('B6', 'Payment adjusted when performed/billed by provider type/facility type/specialty', 'other', true),
  ('B7', 'Provider not certified/eligible to be paid for procedure/service on date of service', 'other', true),
  ('B8', 'Alternative services were available and should have been utilized', 'other', true),
  ('B9', 'Patient is enrolled in a Hospice', 'other', true),
  ('B10', 'Allowed amount reduced because component of basic procedure/test was paid', 'other', true),
  ('B11', 'Claim/service transferred to proper payer/processor', 'other', true),
  ('B12', 'Services not documented in patient''s medical records', 'other', true),
  ('B13', 'Previously paid', 'other', true),
  ('B14', 'Only one visit or consultation per physician per day is covered', 'other', true),
  ('B15', 'Service/procedure requires qualifying service/procedure received and covered', 'other', true),
  ('B16', '''New Patient'' qualifications were not met', 'other', true),
  ('B17', 'Payment adjusted for service not prescribed/prescribed prior to delivery/prescription incomplete', 'missing_info', true),
  ('B18', 'This procedure code and modifier were invalid on the date of service', 'coding_error', true),
  ('B19', 'Claim/service adjusted because of Review Organization finding', 'other', true),
  ('B20', 'Procedure/service partially or fully furnished by another provider', 'other', true),
  ('B21', 'Charges reduced because service/care partially furnished by another physician', 'other', true),
  ('B22', 'This payment is adjusted based on the diagnosis', 'other', true),
  ('B23', 'Procedure billed not authorized per Clinical Laboratory Improvement Amendment (CLIA)', 'lack_of_preauth', true),
  ('D1', 'Claim/service denied. Level of subluxation missing or inadequate', 'missing_info', true),
  ('D2', 'Claim lacks the name, strength, or dosage of the drug furnished', 'other', true),
  ('D3', 'Claim denied: missing info on whether patient owns equipment requiring part/supply', 'missing_info', true),
  ('D4', 'Claim/service does not indicate period of time for which service will be needed', 'other', true),
  ('D5', 'Claim/service denied. Claim lacks individual lab codes included in the test', 'other', true),
  ('D6', 'Claim/service denied. Claim did not include patient''s medical record', 'other', true),
  ('D7', 'Claim/service denied. Claim lacks date of patient''s most recent physician visit', 'other', true),
  ('D8', 'Claim denied. Claim lacks indicator that ''x-ray is available for review''', 'other', true),
  ('D9', 'Claim denied. Claim lacks invoice/statement certifying actual cost of lens', 'other', true),
  ('D10', 'Claim/service denied. Completed physician financial relationship form not on file', 'other', true),
  ('D11', 'Claim lacks completed pacemaker registration form', 'other', true),
  ('D12', 'Claim denied: does not identify who performed purchased diagnostic test/amount charged', 'other', true),
  ('D13', 'Claim denied: performed by facility/supplier where ordering physician has financial interest', 'other', true),
  ('D14', 'Claim lacks indication that plan of treatment is on file', 'other', true),
  ('D15', 'Claim lacks indication that service was supervised or evaluated by physician', 'other', true),
  ('D16', 'Claim lacks prior payer payment information', 'other', true),
  ('D17', 'Claim/Service has invalid non-covered days', 'non_covered_service', true),
  ('D18', 'Claim/Service has missing diagnosis information', 'missing_info', true),
  ('D19', 'Claim/Service lacks Physician/Operative or other supporting documentation', 'missing_info', true),
  ('D20', 'Claim/Service missing service/product information', 'missing_info', true),
  ('D21', 'This (these) diagnosis(es) is (are) missing or are invalid', 'missing_info', true),
  ('D22', 'Reimbursement adjusted for reasons to be provided in separate correspondence', 'other', true),
  ('D23', 'This dual eligible patient covered by Medicare Part D per Medicare Retro-Eligibility', 'other', true),
  ('P1', 'State-mandated Requirement for Property and Casualty', 'other_liability', true),
  ('P2', 'Not a work related injury/illness; not liability of workers'' compensation carrier', 'other_liability', true),
  ('P3', 'Workers'' Compensation case settled; patient responsible via WC ''Medicare set aside''', 'other_liability', true),
  ('P4', 'Workers'' Compensation claim adjudicated non-compensable', 'other_liability', true),
  ('P5', 'Based on payer reasonable and customary fees (Property and Casualty)', 'other_liability', true),
  ('P6', 'Based on entitlement to benefits (Property and Casualty)', 'other_liability', true),
  ('P7', 'Applicable fee schedule/fee database does not contain billed code (Property and Casualty)', 'contractual', true),
  ('P8', 'Claim is under investigation (Property and Casualty)', 'other_liability', true),
  ('P9', 'No available or correlating CPT/HCPCS code to describe service (Property and Casualty)', 'other_liability', true),
  ('P10', 'Payment reduced to zero due to litigation (Property and Casualty)', 'other_liability', true),
  ('P11', 'Disposition of related Property & Casualty claim pending due to litigation', 'other', true),
  ('P12', 'Workers'' compensation jurisdictional fee schedule adjustment', 'contractual', true),
  ('P13', 'Payment reduced/denied based on workers'' compensation jurisdictional regulations', 'other_liability', true),
  ('P14', 'Benefit for Service included in payment/allowance for another service (Property and Casualty)', 'other_liability', true),
  ('P15', 'Workers'' Compensation Medical Treatment Guideline Adjustment', 'other_liability', true),
  ('P16', 'Medical provider not authorized/certified for injured workers in this jurisdiction', 'lack_of_preauth', true),
  ('P17', 'Referral not authorized by attending physician per regulatory requirement (Property and Casualty)', 'lack_of_preauth', true),
  ('P18', 'Procedure not listed in jurisdiction fee schedule; allowance for comparable service', 'contractual', true),
  ('P19', 'Procedure has relative value of zero in jurisdiction fee schedule', 'contractual', true),
  ('P20', 'Service not paid under jurisdiction allowed outpatient facility fee schedule', 'contractual', true),
  ('P21', 'Payment denied based on MPC/PIP Benefits jurisdictional regulations (Property and Casualty Auto)', 'other_liability', true),
  ('P22', 'Payment adjusted based on MPC/PIP Benefits jurisdictional regulations (Property and Casualty Auto)', 'other_liability', true),
  ('P23', 'MPC or PIP Benefits jurisdictional fee schedule adjustment (Property and Casualty Auto)', 'contractual', true),
  ('P24', 'Payment adjusted based on Preferred Provider Organization (PPO) (Property and Casualty)', 'other_liability', true),
  ('P25', 'Payment adjusted based on Medical Provider Network (MPN) (Property and Casualty)', 'other_liability', true),
  ('P26', 'Payment adjusted based on Voluntary Provider network (VPN) (Property and Casualty)', 'other_liability', true),
  ('P27', 'Payment denied based on Liability Coverage Benefits (Property and Casualty Auto)', 'non_covered_service', true),
  ('P28', 'Payment adjusted based on Liability Coverage Benefits (Property and Casualty Auto)', 'non_covered_service', true),
  ('P29', 'Liability Benefits jurisdictional fee schedule adjustment (Property and Casualty Auto)', 'contractual', true),
  ('P30', 'Payment denied for exacerbation; supporting documentation incomplete (Property and Casualty)', 'missing_info', true),
  ('P31', 'Payment denied for exacerbation; treatment exceeds time allowed (Property and Casualty)', 'other_liability', true),
  ('P32', 'Payment adjusted due to Apportionment', 'other', true),
  ('W1', 'Workers'' compensation jurisdictional fee schedule adjustment', 'contractual', false),
  ('W2', 'Payment reduced/denied based on workers'' compensation regulations', 'other_liability', false),
  ('W3', 'Benefit for Service included in payment/allowance for another service', 'other', false),
  ('W4', 'Workers'' Compensation Medical Treatment Guideline Adjustment', 'other_liability', false),
  ('W5', 'Medical provider not authorized/certified for injured workers', 'lack_of_preauth', false),
  ('W6', 'Referral not authorized by attending physician', 'lack_of_preauth', false),
  ('W7', 'Procedure not listed in jurisdiction fee schedule', 'contractual', false),
  ('W8', 'Procedure has relative value of zero in fee schedule', 'contractual', false),
  ('W9', 'Service not paid under jurisdiction allowed outpatient facility fee schedule', 'contractual', false),
  ('Y1', 'Payment denied based on MPC/PIP Benefits', 'other', false)
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description,
    category    = EXCLUDED.category,
    is_active   = EXCLUDED.is_active;
