-- ============================================================
-- Denial Navigator — RARC Code Seed Data (WPC X12)
-- Remittance Advice Remark Codes
-- ============================================================

INSERT INTO rarc_codes (code, description, applicable_cagc) VALUES
('N382', 'Missing/invalid patient date of birth', 'OA'),
('N383', 'Missing/invalid patient gender', 'OA'),
('N384', 'Missing/invalid patient address', 'OA'),
('N385', 'Missing/invalid patient ID/policy number', 'OA'),
('N386', 'Missing/invalid subscriber name', 'OA'),
('N387', 'Missing/invalid member ID', 'OA'),
('N388', 'Missing/invalid group number', 'OA'),
('N389', 'Missing/invalid employer name', 'OA'),
('N390', 'Missing/invalid plan name', 'OA'),
('N401', 'Claim lacks information necessary for processing', 'OA'),
('N402', 'Missing or invalid diagnosis code', 'OA'),
('N403', 'Missing or invalid procedure code', 'OA'),
('N404', 'Missing or invalid date of service', 'OA'),
('N405', 'Missing or invalid place of service code', 'OA'),
('N406', 'Missing or invalid modifier', 'OA'),
('N407', 'Missing or invalid diagnosis pointer', 'OA'),
('N408', 'Missing or invalid linking phrase', 'OA'),
('N409', 'Missing or invalid billing provider information', 'OA'),
('N410', 'Missing or invalid rendering provider information', 'OA'),
('N411', 'Missing or invalid referral number', 'OA'),
('N412', 'Missing or invalid authorization number', 'OA'),
('N413', 'Missing or invalid primary insurance information', 'OA'),
('N414', 'Missing or invalid secondary insurance information', 'OA'),
('N415', 'Missing or invalid tertiary insurance information', 'OA'),
('N416', 'Missing or invalid coordination of benefits information', 'OA'),
('N417', 'Missing or invalid liability insurance information', 'OA'),
('N418', 'Missing or invalid workers compensation information', 'OA'),
('N419', 'Missing or invalid BLN (Blind Line) number', 'OA'),
('N420', 'Missing or invalid claim type', 'OA'),
('N421', 'Missing or invalid frequency code', 'OA'),
('N422', 'Missing or invalid revenue code', 'OA'),
('N423', 'Missing or invalid UB04 form information', 'OA'),
('N424', 'Missing or invalid UB92 form information', 'OA'),
('N425', 'Missing or invalid CMS-1500 form information', 'OA'),
('N426', 'Missing or invalid patient relationship to subscriber', 'OA'),
('N427', 'Missing or invalid patient marital status', 'OA'),
('N428', 'Missing or invalid patient race/ethnicity', 'OA'),
('N429', 'Missing or invalid emergency status', 'OA'),
('N430', 'Missing or critical information is missing or invalid', 'OA'),
('P471', 'Service(s) altered or modified', 'CO'),
('P472', 'Multiple service/procedure on same day', 'CO'),
('P473', 'Billed with a diagnosis requiring medical review', 'CO'),
('P474', 'Billed with a diagnosis requiring medical review - second notice', 'CO'),
('P475', 'Billed with a diagnosis requiring medical review - third notice', 'CO'),
('P476', 'Claim is bundled into another claim', 'CO'),
('P477', 'Duplicate billing', 'CO'),
('P478', 'Duplicate claim', 'CO'),
('P479', 'Billed at a higher fee than usual', 'CO'),
('P480', 'Not covered under current plan', 'CO'),
('P481', 'Service is not covered', 'CO'),
('P482', 'Not medically necessary', 'CO'),
('P483', 'Experimental or investigational', 'CO'),
('P484', 'Not a covered benefit', 'CO'),
('P485', 'Patient not eligible at time of service', 'CO'),
('P486', 'Coverage terminated', 'CO'),
('P487', 'Prior authorization not obtained', 'CO'),
('P488', 'Referral not obtained', 'CO'),
('P489', 'Pre-authorization denied', 'CO'),
('P490', 'Non-covered service', 'CO'),
('P491', 'Service not rendered', 'CO'),
('P492', 'Billed in error', 'CO'),
('P493', 'Not covered because rendered by out-of-network provider', 'CO'),
('P494', 'Not covered because provider not credentialed', 'CO'),
('P495', 'Not covered because not a covered diagnosis', 'CO'),
('P496', 'Not covered because of plan exclusion', 'CO'),
('P497', 'Not covered because annual max reached', 'CO'),
('P498', 'Not covered because lifetime max reached', 'CO'),
('P499', 'Not covered because deductible not met', 'CO'),
('R471', 'Service not covered because it is a welfare benefit', 'OA'),
('R472', 'Billed at a higher rate than prescribed', 'OA'),
('R473', 'Not covered because service was not rendered', 'OA'),
('R474', 'Not covered because of age restriction', 'OA'),
('R475', 'Not covered because cosmetic procedure', 'OA'),
('R476', 'Not covered because counseling-related', 'OA'),
('R477', 'Not covered because elective procedure', 'OA'),
('R478', 'Not covered because service not medically necessary', 'OA'),
('R479', 'Not covered because of research study', 'OA'),
('R480', 'Not covered because out-of-state service', 'OA'),
('R481', 'Not covered because out-of-region service', 'OA'),
('R482', 'Not covered because out-of-coverage area', 'OA'),
('R483', 'Not covered because of dental exclusion', 'OA'),
('R484', 'Not covered because of vision exclusion', 'OA'),
('R485', 'Not covered because of pharmacy exclusion', 'OA'),
('R486', 'Not covered because of inpatient billing for outpatient service', 'OA'),
('R487', 'Not covered because of outpatient billing for inpatient service', 'OA'),
('R488', 'Not covered because of separate deductible', 'OA'),
('R489', 'Not covered because of copayment requirement', 'OA'),
('R490', 'Not covered because of coinsurance requirement', 'OA'),
('R491', 'Not covered because of plan limitation', 'OA'),
('R492', 'Not covered because of network restriction', 'OA'),
('R493', 'Not covered because of tier restriction', 'OA'),
('R494', 'Not covered because of step therapy required', 'OA'),
('R495', 'Not covered because of fail first requirement', 'OA'),
('R496', 'Not covered because of quantity limitation', 'OA'),
('R497', 'Not covered because of dosage limitation', 'OA'),
('R498', 'Not covered because of frequency limitation', 'OA'),
('R499', 'Not covered because of duration limitation', 'OA');
