[package]
name = "denial_db"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "denial_db"
path = "src/lib.rs"

[dependencies]
denial_common = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
