import React, { useEffect, useState } from 'react'
import { useAuth } from '../contexts/AuthContext'

const API = '/api/v1/playbooks'
type PlaybookForm = { name: string; description: string; carc_code: string; cagc: string; payer_name: string; required_action: string; steps: string }
type Playbook = { id: string; name: string; description?: string | null; triggers?: Record<string, unknown>; recommendation?: { required_action?: string }; status: string; version: number }
const blank: PlaybookForm = { name: '', description: '', carc_code: '', cagc: '', payer_name: '', required_action: 'clinical_documentation', steps: '' }

export default function Playbooks() {
  const { can } = useAuth(); const [items, setItems] = useState<Playbook[]>([]); const [form, setForm] = useState<PlaybookForm>(blank); const [notice, setNotice] = useState(''); const [show, setShow] = useState(false)
  const load = () => fetch(API).then(r => r.json()).then((d: unknown) => setItems(Array.isArray(d) ? d as Playbook[] : [])).catch(() => setItems([]))
  useEffect(() => { void load() }, [])
  const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const triggers = Object.fromEntries(Object.entries({ carc_code: form.carc_code, cagc: form.cagc, payer_name: form.payer_name }).filter(([, v]) => v.trim())); const recommendation = { required_action: form.required_action, steps: form.steps.split('\n').map(s => s.trim()).filter(Boolean) }; const r = await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name,description:form.description,triggers,recommendation})}); setNotice(r.ok ? 'Saved as draft. A manager must approve it before it can apply.' : 'Could not save playbook.'); if(r.ok){setForm(blank);setShow(false);load()} }
  const action = async (id: string, suffix: 'approve' | 'archive') => { const r=await fetch(`${API}/${id}/${suffix}`,{method:'POST'}); setNotice(r.ok ? `Playbook ${suffix}d.` : 'Action failed.'); if(r.ok) load() }
  return <div className="page-body">
    <h1 className="page-title">Playbooks</h1>
    <div className="filters-bar"><div><h3 style={{margin:0}}>📘 Institutional Playbooks</h3><p style={{margin:'4px 0',color:'var(--gray-500)'}}>Approved rules provide transparent, deterministic guidance for recurring denials.</p></div>{can.managePlaybooks() && <button className="btn btn-primary" onClick={()=>setShow(!show)}>+ New playbook</button>}</div>
    {notice && <div className="card" style={{marginBottom:12}}><div className="card-body">{notice}</div></div>}
    {show && <div className="card" style={{marginBottom:16}}><div className="card-body"><form onSubmit={save}><div className="form-group"><label>Name</label><input required className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g., Missing authorization workflow"/></div><div className="form-group"><label>Description</label><textarea className="form-input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}><div className="form-group"><label>CARC</label><input className="form-input" value={form.carc_code} onChange={e=>setForm({...form,carc_code:e.target.value})}/></div><div className="form-group"><label>CAGC</label><input className="form-input" value={form.cagc} onChange={e=>setForm({...form,cagc:e.target.value})}/></div><div className="form-group"><label>Payer</label><input className="form-input" value={form.payer_name} onChange={e=>setForm({...form,payer_name:e.target.value})}/></div></div><div className="form-group"><label>Recommended action</label><select className="form-select" value={form.required_action} onChange={e=>setForm({...form,required_action:e.target.value})}><option value="clinical_documentation">Clinical documentation</option><option value="coding_correction">Coding correction</option><option value="appeal">Appeal</option><option value="bill_patient">Bill patient</option></select></div><div className="form-group"><label>Steps (one per line)</label><textarea className="form-input" value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})}/></div><button className="btn btn-primary">Save draft</button></form></div></div>}
    <div className="card"><div className="table-container"><table><thead><tr><th>Name</th><th>Triggers</th><th>Action</th><th>Status</th><th>Version</th><th></th></tr></thead><tbody>{items.length===0?<tr><td colSpan={6} style={{textAlign:'center',padding:24}}>No playbooks yet</td></tr>:items.map(p=><tr key={p.id}><td><strong>{p.name}</strong><div style={{fontSize:'.8rem',color:'var(--gray-500)'}}>{p.description}</div></td><td>{Object.entries(p.triggers||{}).map(([k,v])=>`${k.replace('_',' ')}: ${v}`).join(' · ') || 'Any denial'}</td><td>{p.recommendation?.required_action?.replace(/_/g,' ') || '—'}</td><td><span className={`badge badge-${p.status}`}>{p.status}</span></td><td>v{p.version}</td><td>{can.managePlaybooks()&&p.status==='draft'&&<button className="btn btn-sm btn-primary" onClick={()=>action(p.id,'approve')}>Approve</button>}{can.managePlaybooks()&&p.status!=='archived'&&<button className="btn btn-sm" style={{marginLeft:6}} onClick={()=>action(p.id,'archive')}>Archive</button>}</td></tr>)}</tbody></table></div></div>
  </div>
}
