// This file is generated by crates/api-gateway/openapi/generate.py. Do not edit.
// Regenerate with: pnpm generate:api

export type ApiOperation = keyof ApiOperations

export interface ApiOperations {
  "GET /api/v1/analyses": { query?: { "denial_id"?: string; "claim_id"?: string; "limit"?: number } };
  "POST /api/v1/analyses/generate": { body: { "denial_id": string; "temperature"?: number } };
  "POST /api/v1/analyses/generate-jobs": { body: { "denial_id": string; "temperature"?: number } };
  "GET /api/v1/analyses/generate-jobs/{job_id}": { path: { "job_id": string } };
  "GET /api/v1/analyses/status": Record<string, never>;
  "POST /api/v1/analyses/store": { body: { "denial_id": string; "claim_id": string; "model_name": string; "raw_prompt": string; "raw_response": string; "parsed_result": Record<string, unknown>; "prompt_tokens"?: number; "completion_tokens"?: number; "total_tokens"?: number } };
  "GET /api/v1/appeals": { query?: { "outcome_status"?: string; "resolution_type"?: string; "category"?: "appeal" | "worklist"; "assigned_user_id"?: string; "sort"?: "created_at" | "expected_recovery"; "descending"?: boolean; "limit"?: number; "offset"?: number } };
  "POST /api/v1/appeals": { body: { "denial_id": string; "resolution_type": string; "notes"?: string } };
  "POST /api/v1/appeals/bulk": { body: { "denial_ids": Array<string>; "resolution_type": string } };
  "GET /api/v1/appeals/{appeal_id}": { path: { "appeal_id": string } };
  "PATCH /api/v1/appeals/{appeal_id}": { path: { "appeal_id": string }; body: { "outcome_status"?: string; "notes"?: string; "payer_response"?: string; "final_outcome"?: string; "submission_method"?: "portal" | "fax" | "mail" | "email"; "payer_confirmation_number"?: string } };
  "POST /api/v1/appeals/{appeal_id}/assign": { path: { "appeal_id": string }; body: { "assigned_user_id"?: string } };
  "GET /api/v1/appeals/{appeal_id}/letter": { path: { "appeal_id": string } };
  "GET /api/v1/appeals/{appeal_id}/packet": { path: { "appeal_id": string } };
  "POST /api/v1/appeals/{appeal_id}/packet": { path: { "appeal_id": string } };
  "POST /api/v1/appeals/{appeal_id}/packet/approve": { path: { "appeal_id": string } };
  "GET /api/v1/appeals/{appeal_id}/packet/download": { path: { "appeal_id": string } };
  "GET /api/v1/audit": { query?: { "action"?: string; "resource_type"?: string; "user_id"?: string; "username"?: string; "start_date"?: string; "end_date"?: string; "limit"?: number; "offset"?: number } };
  "GET /api/v1/audit/actors": Record<string, never>;
  "GET /api/v1/audit/stats": Record<string, never>;
  "POST /api/v1/auth/change-password": { body: { "current_password": string; "new_password": string } };
  "POST /api/v1/auth/login": { body: { "username": string; "password": string; "organization_id"?: string } };
  "POST /api/v1/auth/login/totp": { body: { "code": string } };
  "GET /api/v1/auth/me": Record<string, never>;
  "POST /api/v1/auth/register": { body: { "username": string; "email": string; "password": string; "full_name"?: string; "role": "system_admin" | "security_admin" | "revenue_cycle_manager" | "billing_specialist" | "coding_specialist" | "auditor" | "read_only" } };
  "POST /api/v1/auth/totp/confirm": { body: { "code": string } };
  "POST /api/v1/auth/totp/enroll": Record<string, never>;
  "GET /api/v1/claims": { query?: { "status"?: string; "q"?: string; "limit"?: number; "offset"?: number } };
  "POST /api/v1/claims": { body: { "claim_number": string; "patient_id": string; "payer_name": string; "total_charge": number; "icd_10_codes"?: Array<string> } };
  "GET /api/v1/claims/dashboard/stats": Record<string, never>;
  "GET /api/v1/claims/export.csv": { query?: { "status"?: string; "q"?: string } };
  "GET /api/v1/claims/unanswered": Record<string, never>;
  "GET /api/v1/claims/{claim_id}": { path: { "claim_id": string } };
  "PATCH /api/v1/claims/{claim_id}": { path: { "claim_id": string }; body: { "status"?: string; "total_paid"?: number; "total_adjustment"?: number } };
  "POST /api/v1/claims/{claim_id}/followups": { path: { "claim_id": string }; body: { "action": "status_inquiry" | "resubmitted" | "payer_contact"; "note"?: string } };
  "GET /api/v1/denials": { query?: { "status"?: string; "carc_code"?: string; "payer_name"?: string; "min_amount"?: number; "max_amount"?: number; "min_age_days"?: number; "max_age_days"?: number; "owner"?: string; "facility_type_code"?: string; "cagc"?: string; "claim_id"?: string; "q"?: string; "priority"?: boolean; "sort"?: "amount" | "deadline" | "created"; "descending"?: boolean; "cursor"?: string; "limit"?: number; "offset"?: number } };
  "GET /api/v1/denials/aging-buckets": Record<string, never>;
  "GET /api/v1/denials/appeal-windows": Record<string, never>;
  "PUT /api/v1/denials/appeal-windows": { body: { "payer_name": string; "appeal_window_days": number; "notes"?: string } };
  "GET /api/v1/denials/bulk-carc": Record<string, never>;
  "GET /api/v1/denials/by-payer": Record<string, never>;
  "GET /api/v1/denials/by-root-cause": Record<string, never>;
  "GET /api/v1/denials/carc-options": { query?: { "status"?: string } };
  "GET /api/v1/denials/deadline-rules": Record<string, never>;
  "PUT /api/v1/denials/deadline-rules": { body: { "payer_name": string; "deadline_type": "timely_filing" | "corrected_claim" | "reconsideration" | "appeal_level_2" | "payer_response"; "days": number; "notes"?: string } };
  "DELETE /api/v1/denials/deadline-rules/{rule_id}": { path: { "rule_id": string } };
  "GET /api/v1/denials/financial-summary": Record<string, never>;
  "GET /api/v1/denials/resolution-timing": Record<string, never>;
  "GET /api/v1/denials/{denial_id}": { path: { "denial_id": string } };
  "PATCH /api/v1/denials/{denial_id}": { path: { "denial_id": string }; body: { "status"?: string; "appeal_deadline"?: string } };
  "GET /api/v1/denials/{denial_id}/attachments": { path: { "denial_id": string } };
  "POST /api/v1/denials/{denial_id}/attachments": { path: { "denial_id": string }; body: FormData };
  "GET /api/v1/denials/{denial_id}/attachments/{attachment_id}": { path: { "denial_id": string; "attachment_id": string } };
  "DELETE /api/v1/denials/{denial_id}/attachments/{attachment_id}": { path: { "denial_id": string; "attachment_id": string } };
  "GET /api/v1/denials/{denial_id}/interactions": { path: { "denial_id": string } };
  "POST /api/v1/denials/{denial_id}/interactions": { path: { "denial_id": string }; body: { "channel": string; "summary": string; "occurred_at"?: string; "reference_number"?: string; "representative"?: string; "follow_up_on"?: string } };
  "POST /api/v1/denials/{denial_id}/interactions/{interaction_id}/complete": { path: { "denial_id": string; "interaction_id": string } };
  "GET /api/v1/feedback": { query?: { "ai_analysis_id"?: string; "accepted"?: boolean; "limit"?: number } };
  "POST /api/v1/feedback": { body: { "ai_analysis_id": string; "user_id"?: string; "rating"?: number; "accepted"?: boolean; "user_edits"?: Record<string, unknown>; "action_taken"?: string; "was_paid_on_resubmit"?: boolean; "resubmit_result"?: string; "feedback_text"?: string } };
  "GET /api/v1/feedback/analytics": Record<string, never>;
  "GET /api/v1/feedback/similar-resolved": { query?: { "denial_id" : string; "limit"?: number } };
  "GET /api/v1/ingestion/history": { query?: { "limit"?: number } };
  "POST /api/v1/ingestion/ingest": Record<string, never>;
  "POST /api/v1/ingestion/log": { body: Record<string, unknown> };
  "GET /api/v1/ingestion/provider-adjustments": { query?: { "claim_number"?: string; "reason_code"?: string; "limit"?: number } };
  "GET /api/v1/ingestion/provider-adjustments/summary": Record<string, never>;
  "POST /api/v1/ingestion/store": { body: { "file_name": string; "file_hash": string; "file_size"?: number; "claims": Array<Record<string, unknown>>; "denials": Array<Record<string, unknown>> } };
  "POST /api/v1/ingestion/upload": { body: FormData };
  "GET /api/v1/knowledge/documents": { query?: { "source_type"?: string; "status"?: string; "expiry"?: "expiring_soon" | "expired_active"; "expiring_within_days"?: number; "limit"?: number } };
  "POST /api/v1/knowledge/documents": { body: { "title": string; "source_type": string; "payer_id"?: string; "payer_name"?: string; "effective_date"?: string; "content"?: string } };
  "GET /api/v1/knowledge/documents/expiry-summary": { query?: { "within_days"?: number } };
  "POST /api/v1/knowledge/documents/upload": { query?: { "title"?: string; "source_type"?: string; "payer_name"?: string }; body: FormData };
  "GET /api/v1/knowledge/documents/{document_id}": { path: { "document_id": string } };
  "DELETE /api/v1/knowledge/documents/{document_id}": { path: { "document_id": string }; query?: { "purge"?: boolean } };
  "POST /api/v1/knowledge/documents/{document_id}/content": { path: { "document_id": string }; body: { "content": string } };
  "POST /api/v1/knowledge/documents/{document_id}/supersede": { path: { "document_id": string }; body: { "new_document_id": string } };
  "POST /api/v1/knowledge/reindex": { body: { "limit"?: number } };
  "POST /api/v1/knowledge/search": { body: { "query": string; "top_k"?: number; "filters"?: Record<string, unknown> } };
  "GET /api/v1/notifications": { query?: { "unread_only"?: boolean; "limit"?: number } };
  "POST /api/v1/notifications/generate-digests": Record<string, never>;
  "POST /api/v1/notifications/read-all": Record<string, never>;
  "POST /api/v1/notifications/{notification_id}/read": { path: { "notification_id": string } };
  "GET /api/v1/overpayments": { query?: { "status"?: "identified" | "refunded" | "recouped" | "disputed" } };
  "POST /api/v1/overpayments/{id}/status": { path: { "id": string }; body: { "status": "identified" | "refunded" | "recouped" | "disputed"; "note"?: string } };
  "GET /api/v1/payers": Record<string, never>;
  "POST /api/v1/payers": { body: { "name": string } };
  "DELETE /api/v1/payers/{payer_id}": { path: { "payer_id": string } };
  "POST /api/v1/payers/{payer_id}/aliases": { path: { "payer_id": string }; body: { "alias": string; "kind"?: "name" | "payer_id" } };
  "DELETE /api/v1/payers/{payer_id}/aliases/{alias_id}": { path: { "payer_id": string; "alias_id": string } };
  "GET /api/v1/playbooks": { query?: { "status"?: string } };
  "POST /api/v1/playbooks": { body: { "name": string; "description"?: string; "triggers"?: Record<string, unknown>; "recommendation"?: Record<string, unknown> } };
  "POST /api/v1/playbooks/test": { body: { "carc_code"?: string; "cagc"?: string; "payer_name"?: string } };
  "POST /api/v1/playbooks/{id}": { path: { "id": string }; body: { "name": string; "description"?: string; "triggers"?: Record<string, unknown>; "recommendation"?: Record<string, unknown> } };
  "POST /api/v1/playbooks/{id}/approve": { path: { "id": string } };
  "POST /api/v1/playbooks/{id}/archive": { path: { "id": string } };
  "GET /api/v1/reference/summary": Record<string, never>;
  "POST /api/v1/reference/{kind}/clear": { path: { "kind": "carc" | "rarc" | "icd10" | "cpt" | "hcpcs" | "modifier" }; body: { "confirm": boolean } };
  "POST /api/v1/reference/{kind}/delete": { path: { "kind": "carc" | "rarc" | "icd10" | "cpt" | "hcpcs" | "modifier" }; body: { "code": string } };
  "POST /api/v1/reference/{kind}/import": { path: { "kind": "carc" | "rarc" | "icd10" | "cpt" | "hcpcs" | "modifier" }; body: FormData };
  "GET /api/v1/reference/{kind}/search": { path: { "kind": "carc" | "rarc" | "icd10" | "cpt" | "hcpcs" | "modifier" }; query?: { "q"?: string; "limit"?: number; "offset"?: number } };
  "GET /api/v1/retention/ai": Record<string, never>;
  "POST /api/v1/retention/ai/prune": { body: { "older_than_days"?: number; "confirm": boolean } };
  "GET /api/v1/retention/audit": Record<string, never>;
  "POST /api/v1/retention/audit/prune": { body: { "older_than_days"?: number; "confirm": boolean } };
  "GET /api/v1/settings/overpayment-refund": Record<string, never>;
  "PUT /api/v1/settings/overpayment-refund": { body: { "days": number } };
  "GET /api/v1/settings/phi-disclosure": Record<string, never>;
  "PUT /api/v1/settings/phi-disclosure": { body: { "level": "none" | "deidentified" | "limited_phi" | "full_context" } };
  "GET /api/v1/settings/write-off-approval": Record<string, never>;
  "PUT /api/v1/settings/write-off-approval": { body: { "threshold": number } };
  "GET /api/v1/system/health": Record<string, never>;
  "GET /api/v1/users": Record<string, never>;
  "GET /api/v1/users/assignable": Record<string, never>;
  "GET /api/v1/users/{user_id}": { path: { "user_id": string } };
  "PATCH /api/v1/users/{user_id}": { path: { "user_id": string }; body: { "email"?: string; "full_name"?: string; "role"?: string; "is_active"?: boolean } };
  "DELETE /api/v1/users/{user_id}": { path: { "user_id": string } };
  "POST /api/v1/users/{user_id}/password": { path: { "user_id": string }; body: { "new_password": string } };
  "POST /api/v1/users/{user_id}/totp": { path: { "user_id": string }; body: { "totp_required": boolean } };
  "POST /api/v1/users/{user_id}/totp/reset": { path: { "user_id": string } };
  "GET /api/v1/write-offs": { query?: { "status"?: "pending" | "approved" | "rejected" } };
  "POST /api/v1/write-offs/{id}/approve": { path: { "id": string }; body?: { "note"?: string } };
  "POST /api/v1/write-offs/{id}/reject": { path: { "id": string }; body: { "note": string } };
}

export type ApiRequestOptions<Operation extends ApiOperation> = ApiOperations[Operation] & {
  signal?: AbortSignal
  headers?: HeadersInit
}

export class ApiError extends Error {
  constructor(public readonly response: Response, public readonly payload: unknown) {
    super(`API request failed (${response.status})`)
    this.name = 'ApiError'
  }
}

/** Small fetch client. The app's fetch wrapper supplies bearer auth. */
export class ApiClient {
  constructor(private readonly baseUrl = '') {}

  async request<Operation extends ApiOperation, Response = unknown>(
    operation: Operation,
    options: ApiRequestOptions<Operation> = {} as ApiRequestOptions<Operation>,
  ): Promise<Response> {
    const [method, template] = operation.split(' ', 2) as [string, string]
    const pathValues = (options as { path?: Record<string, string | number> }).path || {}
    const path = template.replace(/{([^}]+)}/g, (_, key) => encodeURIComponent(String(pathValues[key])))
    const query = (options as { query?: Record<string, string | number | boolean | undefined> }).query
    const search = new URLSearchParams()
    if (query) for (const [key, value] of Object.entries(query)) if (value !== undefined) search.set(key, String(value))
    const body = (options as { body?: unknown }).body
    const headers = new Headers(options.headers)
    const init: RequestInit = { method, headers, signal: options.signal }
    if (body instanceof FormData) init.body = body
    else if (body !== undefined) { headers.set('Content-Type', 'application/json'); init.body = JSON.stringify(body) }
    const response = await fetch(`${this.baseUrl}${path}${search.size ? `?${search}` : ''}`, init)
    if (response.status === 204) return undefined as Response
    const payload = await response.json().catch(() => undefined)
    if (!response.ok) throw new ApiError(response, payload)
    return payload as Response
  }
}

export const api = new ApiClient()
